name = "OkRegistry"
uuid = "86e7831a-6f1f-4f41-b710-281fd69cacb1"
repo = "https://github.com/okatsn/OkRegistry.git"
description = "A julia local registry"

[packages]
d0c9a04e-d1fd-4d35-a387-089b7121b945 = { name = "Shorthands", path = "S/Shorthands" }
