name = "OkRegistry"
uuid = "86e7831a-6f1f-4f41-b710-281fd69cacb1"
repo = "https://github.com/okatsn/OkRegistry.git"
description = "A julia local registry"

[packages]
2060839e-1c32-41f2-b945-b79b1f5cc0e8 = { name = "OkExpressions", path = "O/OkExpressions" }
2c042965-b292-4a40-a4a9-3abf2d00bee5 = { name = "FileTools", path = "F/FileTools" }
2e886b56-b55e-403a-a2d0-ccbf75d993da = { name = "DataFrameTools", path = "D/DataFrameTools" }
38290ba8-8fbe-457b-bf75-0e4980da3840 = { name = "OkPkgTemplates", path = "O/OkPkgTemplates" }
4502ade7-0b84-4acc-96da-75e5ce1d0abd = { name = "HypertextTools", path = "H/HypertextTools" }
4acf06e8-6b0e-4a57-aafd-adf19fd274eb = { name = "OkMD", path = "O/OkMD" }
4e74b330-6242-4c7a-bc50-5dcf56e2fdec = { name = "OkMakieToolkits", path = "O/OkMakieToolkits" }
7016d903-ac20-4882-9d97-75c232100024 = { name = "SmallDatasetMaker", path = "S/SmallDatasetMaker" }
711c5545-762e-4f29-8c0d-76adcc314cdc = { name = "FSDatasets", path = "F/FSDatasets" }
8567d2c9-0786-49d4-a67b-7077e6cb99ca = { name = "OkMLModels", path = "O/OkMLModels" }
92a3a819-b5fa-4251-b583-c8bfed228d45 = { name = "SWCDatasets", path = "S/SWCDatasets" }
ab5b03c2-6ccc-4282-bdb8-07112b9001f0 = { name = "SWCForecast", path = "S/SWCForecast" }
ade42d9a-f0a7-4d7c-9f72-e1874134871e = { name = "TestTagBot", path = "T/TestTagBot" }
b25a35d4-863d-483c-9fa1-95480bd075d2 = { name = "OkFiles", path = "O/OkFiles" }
c318fce2-6087-4413-a694-e8b62f046540 = { name = "OkVectorScales", path = "O/OkVectorScales" }
d0c9a04e-d1fd-4d35-a387-089b7121b945 = { name = "Shorthands", path = "S/Shorthands" }
d9c8f7ca-66b2-433f-ab74-835b361b75b3 = { name = "TWAISWCF", path = "T/TWAISWCF" }
f25bfc00-93e4-48b9-89c1-3948a036d4be = { name = "SWCForecastBase", path = "S/SWCForecastBase" }
