name = "OkRegistry"
uuid = "86e7831a-6f1f-4f41-b710-281fd69cacb1"
repo = "https://github.com/okatsn/OkRegistry.git"
description = "A julia local registry"

[packages]
13790f54-d860-4895-b730-45df7ac0a90b = { name = "OkValueReplacer", path = "O/OkValueReplacer" }
2059b88b-3fb9-401b-8059-181c8104de72 = { name = "SWCPlayground", path = "S/SWCPlayground" }
2060839e-1c32-41f2-b945-b79b1f5cc0e8 = { name = "OkExpressions", path = "O/OkExpressions" }
24510c62-9d45-4479-942d-3b577217595b = { name = "SWCFluxDeps", path = "S/SWCFluxDeps" }
2c042965-b292-4a40-a4a9-3abf2d00bee5 = { name = "FileTools", path = "F/FileTools" }
2e886b56-b55e-403a-a2d0-ccbf75d993da = { name = "DataFrameTools", path = "D/DataFrameTools" }
2efd5ccf-8713-4cce-9981-56ece9225c34 = { name = "GEMSMagTIP", path = "G/GEMSMagTIP" }
305ee1c2-282c-4917-94ba-32dcc37024a6 = { name = "OkStartUp", path = "O/OkStartUp" }
32148328-147a-4c3a-aded-c727b77b4e74 = { name = "CorpusCleanerForTWLaws", path = "C/CorpusCleanerForTWLaws" }
34127a1e-43e2-4f4e-97ac-74f3581abec9 = { name = "ProjectLawMaster", path = "P/ProjectLawMaster" }
34c9f1bc-122f-4934-a8b7-538be05c4fb7 = { name = "MyUtilBox", path = "M/MyUtilBox" }
38290ba8-8fbe-457b-bf75-0e4980da3840 = { name = "OkPkgTemplates", path = "O/OkPkgTemplates" }
42c3750f-3b15-406e-9cb1-f05d2df8c96f = { name = "OkTableTools", path = "O/OkTableTools" }
44fb8f6e-77e3-42fb-a351-fd44f2ba0634 = { name = "OkDataFrameTools", path = "O/OkDataFrameTools" }
4502ade7-0b84-4acc-96da-75e5ce1d0abd = { name = "HypertextTools", path = "H/HypertextTools" }
4acf06e8-6b0e-4a57-aafd-adf19fd274eb = { name = "OkMD", path = "O/OkMD" }
4e730273-489a-4dfd-9ca2-bebabcd3c278 = { name = "OkInformationalAnalysis", path = "O/OkInformationalAnalysis" }
4e74b330-6242-4c7a-bc50-5dcf56e2fdec = { name = "OkMakieToolkits", path = "O/OkMakieToolkits" }
5ac41729-0616-47d0-b24e-40b588cdc0a8 = { name = "ReadMatlabDocstrings", path = "R/ReadMatlabDocstrings" }
5eb89c91-2e2f-4632-ba7c-3ec58ab78207 = { name = "OkRegistrator", path = "O/OkRegistrator" }
7016d903-ac20-4882-9d97-75c232100024 = { name = "SmallDatasetMaker", path = "S/SmallDatasetMaker" }
70383841-2333-46ca-adf2-3d6ff66a2e6b = { name = "MolchanCB", path = "M/MolchanCB" }
711c5545-762e-4f29-8c0d-76adcc314cdc = { name = "FSDatasets", path = "F/FSDatasets" }
760a1398-8f00-4da5-9475-268514cb6295 = { name = "OkReadGSheet", path = "O/OkReadGSheet" }
8567d2c9-0786-49d4-a67b-7077e6cb99ca = { name = "OkMLModels", path = "O/OkMLModels" }
8edd2f2a-3081-48b8-b943-5251c412605e = { name = "EventSpaceAlgebra", path = "E/EventSpaceAlgebra" }
92a3a819-b5fa-4251-b583-c8bfed228d45 = { name = "SWCDatasets", path = "S/SWCDatasets" }
9c7ade6c-5fb5-4442-8c75-5d5cb13b77a3 = { name = "OkDevContainerTemplates", path = "O/OkDevContainerTemplates" }
ab5b03c2-6ccc-4282-bdb8-07112b9001f0 = { name = "SWCForecast", path = "S/SWCForecast" }
add5ede0-49b9-4840-ac63-6ca6386cff5c = { name = "OkEMailSender", path = "O/OkEMailSender" }
ade42d9a-f0a7-4d7c-9f72-e1874134871e = { name = "TestTagBot", path = "T/TestTagBot" }
ae1ef8a7-b62b-4b98-a332-ad23a8f1746c = { name = "OkHypertextTools", path = "O/OkHypertextTools" }
b25a35d4-863d-483c-9fa1-95480bd075d2 = { name = "OkFiles", path = "O/OkFiles" }
b38d3104-45cc-42ed-bfee-2aefedd5b40b = { name = "CWBProjectSummaryDatasets", path = "C/CWBProjectSummaryDatasets" }
baabcd0e-1760-42d9-85cb-3fb569e66d9a = { name = "OkImageCropper", path = "O/OkImageCropper" }
bf75f91d-8d33-4f2c-bf9d-6eaba12b5f3c = { name = "OkValueSegments", path = "O/OkValueSegments" }
c318fce2-6087-4413-a694-e8b62f046540 = { name = "OkVectorScales", path = "O/OkVectorScales" }
d0c9a04e-d1fd-4d35-a387-089b7121b945 = { name = "Shorthands", path = "S/Shorthands" }
d200e52a-f1cf-47db-803e-afe27b9c9524 = { name = "FarPointStatistics", path = "F/FarPointStatistics" }
d741b33f-378c-4fda-a3ef-81fb108a0236 = { name = "SWCExampleDatasets", path = "S/SWCExampleDatasets" }
d9c8f7ca-66b2-433f-ab74-835b361b75b3 = { name = "TWAISWCF", path = "T/TWAISWCF" }
e02d82d9-7e7e-46f3-9a6c-b9afd88f5ac7 = { name = "TWGEMSDatasets", path = "T/TWGEMSDatasets" }
e7521825-5d6b-4d2d-b9e2-9f70533e6f0b = { name = "WorkingScopes", path = "W/WorkingScopes" }
e85a2721-9ec6-4204-992d-01b2e59f22bb = { name = "OkTexHelper", path = "O/OkTexHelper" }
ebde9838-6584-4548-b79e-429a239baf90 = { name = "GeoEMTIPDemonstration", path = "G/GeoEMTIPDemonstration" }
f25bfc00-93e4-48b9-89c1-3948a036d4be = { name = "SWCForecastBase", path = "S/SWCForecastBase" }
fa63e605-4ca0-440e-9899-f71f0f6b0a21 = { name = "OkNestedDicts", path = "O/OkNestedDicts" }
